# Generated by Django 5.1.6 on 2025-02-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlyuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='onlyuser_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='onlyuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='onlyuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='onlyuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='onlyuser_set', to='auth.permission'),
        ),
    ]
